// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAflNzSCZoiGlSLqRLJolT1-a1W87fRqck',
    appId: '1:719712897114:web:00a2a111355264c36eb063',
    messagingSenderId: '719712897114',
    projectId: 'splitwise-clone-9f994',
    authDomain: 'splitwise-clone-9f994.firebaseapp.com',
    storageBucket: 'splitwise-clone-9f994.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3NbZF-MaJ_Z6fCIXRj68sasr0QuK16Vg',
    appId: '1:719712897114:android:37a09ccfc67fcdec6eb063',
    messagingSenderId: '719712897114',
    projectId: 'splitwise-clone-9f994',
    storageBucket: 'splitwise-clone-9f994.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfJJTLpuFw67bq54rfP-ufALAEdXqBnUE',
    appId: '1:719712897114:ios:384884c0686d56b86eb063',
    messagingSenderId: '719712897114',
    projectId: 'splitwise-clone-9f994',
    storageBucket: 'splitwise-clone-9f994.firebasestorage.app',
    iosBundleId: 'com.example.splitwiseClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfJJTLpuFw67bq54rfP-ufALAEdXqBnUE',
    appId: '1:719712897114:ios:384884c0686d56b86eb063',
    messagingSenderId: '719712897114',
    projectId: 'splitwise-clone-9f994',
    storageBucket: 'splitwise-clone-9f994.firebasestorage.app',
    iosBundleId: 'com.example.splitwiseClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAflNzSCZoiGlSLqRLJolT1-a1W87fRqck',
    appId: '1:719712897114:web:834e9bb6d0ac8de26eb063',
    messagingSenderId: '719712897114',
    projectId: 'splitwise-clone-9f994',
    authDomain: 'splitwise-clone-9f994.firebaseapp.com',
    storageBucket: 'splitwise-clone-9f994.firebasestorage.app',
  );
}
